# Generated by Django 2.1 on 2020-06-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_datetimetamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='datetimetamp',
        ),
    ]
